# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59b771d1e67c6b2714e1d211461d69e11560ca347c038aa8095d8535fd7a8c9a765651dc188ca448862f8864f38d5c28994de91d134fbcbee0b2081ed3d591b6

test:
  secret_key_base: 153f3de5032b9ebc2c5f65a19ecf5fc0cdf2df59c30064087ae3195e09a3be5473f9e0e82ea52ca724efd33b36032f35ca167e2a47cc5ec250f38a959aba1c14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
